### PR TITLE
Add design

### PR DESCRIPTION
**Pull request by SamaritaninS**

### CODE REVIEW

**Comment by SamaritaninS** [comment]
Самсонов Валентин группа 853503
Проект - Group expenses app.
https://wireframepro.mockflow.com/view/M88ba0523b923f6d865338af4d8d2e1ae1620214898855#/page/41cb40474cc64401a06a937d442be405

**Comment by gmltA** [comment]
That's a <kbd>6</kbd>. Tell me if you are ok with that.

**Comment by SamaritaninS** [comment]
I am agree

**Comment by SamaritaninS** [comment]
> That's a 6. Tell me if you are ok with that.

I am agree

**Review by gmltA — APPROVED** [review]

**Pull request closed without merging**
